import Foundation

/// App de la que procede un contenido copiado.
public struct SourceApp: Equatable, Sendable {
    public var bundleID: String
    public var name: String

    public init(bundleID: String, name: String) {
        self.bundleID = bundleID
        self.name = name
    }
}

/// Convierte una fotografía del portapapeles en la decisión de guardarla o no.
///
/// Toda la política de captura vive aquí y en ningún otro sitio: qué contenido
/// se ignora, de qué tipo es y a qué app se atribuye. No conoce `NSPasteboard`
/// ni la base de datos, así que se puede probar entero sin ninguno de los dos.
public struct CaptureEngine: Sendable {
    public var settings: CaptureSettings
    public var deviceID: UUID

    public init(settings: CaptureSettings, deviceID: UUID) {
        self.settings = settings
        self.deviceID = deviceID
    }

    public func decide(
        _ snapshot: PasteboardSnapshot,
        lastChangeCount: Int,
        frontmost: SourceApp?,
        now: Date = Date()
    ) -> CaptureDecision {
        guard snapshot.changeCount != lastChangeCount else {
            return .skip(.unchanged)
        }

        // El contenido sensible se comprueba antes que la pausa y que las
        // exclusiones a propósito: son reglas duras, no preferencias, y no deben
        // depender del estado en que se encuentre la app.
        if snapshot.types.contains(PasteboardTypes.concealed) {
            return .skip(.concealed)
        }
        if snapshot.types.contains(PasteboardTypes.transient)
            || snapshot.types.contains(PasteboardTypes.autoGenerated) {
            return .skip(.transient)
        }

        let source = resolveSource(snapshot: snapshot, frontmost: frontmost)

        if let bundleID = source?.bundleID, settings.excludedBundleIDs.contains(bundleID) {
            return .skip(.excludedApp)
        }
        if settings.isPaused {
            return .skip(.paused)
        }
        // Ficheros e imágenes llegan en M2. Se descarta explícitamente en vez de
        // caer al texto: guardar la ruta de un fichero como si fuera una nota es
        // peor que no guardar nada.
        if snapshot.types.contains(PasteboardTypes.fileURL) {
            return .skip(.unsupportedType)
        }

        let text = snapshot.string
        if let text, text.utf8.count > settings.maxTextBytes {
            return .skip(.tooLarge)
        }

        return buildItem(snapshot: snapshot, text: text, source: source, now: now)
    }

    // MARK: - Detalle

    /// Lo que declara la app de origen gana sobre lo que esté en primer plano:
    /// si la app dice de dónde viene el contenido, sabe más que nosotros.
    ///
    /// Solo se recurre a `frontmost` cuando no hay declaración, que es el caso
    /// habitual. Su punto débil: si copias y cambias de app antes del siguiente
    /// sondeo, la atribución sale mal.
    private func resolveSource(
        snapshot: PasteboardSnapshot,
        frontmost: SourceApp?
    ) -> SourceApp? {
        guard let declared = snapshot.declaredSourceBundleID, !declared.isEmpty else {
            return frontmost
        }
        // Si el bundle ID declarado coincide con el de primer plano, se conserva
        // el nombre legible, que la declaración no trae.
        if let frontmost, frontmost.bundleID == declared {
            return frontmost
        }
        return SourceApp(bundleID: declared, name: declared)
    }

    private func buildItem(
        snapshot: PasteboardSnapshot,
        text: String?,
        source: SourceApp?,
        now: Date
    ) -> CaptureDecision {
        let trimmed = text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""

        let kind: ContentKind
        if snapshot.types.contains(PasteboardTypes.url), !trimmed.isEmpty {
            // Por delante del RTF: un enlace copiado de una página web llega
            // como RTF + HTML + texto, y tratarlo como texto con formato
            // perdería que es un enlace.
            kind = .url
        } else if snapshot.rtf != nil {
            kind = .richText
        } else if !trimmed.isEmpty, URLDetector.isWholeURL(trimmed) {
            kind = .url
        } else if !trimmed.isEmpty {
            kind = .text
        } else {
            return .skip(.empty)
        }

        // El texto plano se conserva siempre, incluso en el contenido con
        // formato: es lo que indexa FTS5, y sin él un fragmento de RTF sería
        // imposible de encontrar buscando.
        let plainText = text
        let richData = kind == .richText ? snapshot.rtf : nil
        let hash = if let richData {
            ContentHasher.hash(richText: trimmed, rtf: richData)
        } else {
            ContentHasher.hash(text: trimmed)
        }

        let item = ClipboardItem(
            contentHash: hash,
            kind: kind,
            plainText: plainText,
            richData: richData,
            byteSize: (plainText?.utf8.count ?? 0) + (richData?.count ?? 0),
            sourceBundleID: source?.bundleID,
            sourceAppName: source?.name,
            urlHost: kind == .url ? ClipboardItem.extractHost(from: trimmed) : nil,
            sourceDeviceID: deviceID,
            createdAt: now,
            updatedAt: now
        )
        return .capture(item)
    }
}
