import Foundation

/// Fotografía del portapapeles en un instante, sin nada específico de la
/// plataforma.
///
/// Existe para que `CaptureEngine` pueda decidir qué hacer sin tocar
/// `NSPasteboard` ni `UIPasteboard`: la extracción vive en cada app, la política
/// vive aquí y se puede probar entera con `swift test`.
public struct PasteboardSnapshot: Equatable, Sendable {
    /// Contador que el sistema incrementa en cada escritura. Es lo único que
    /// distingue "no ha pasado nada" de "hay contenido nuevo idéntico".
    public var changeCount: Int

    /// Identificadores de tipo en crudo, tal cual los declara el portapapeles.
    /// Se guardan sin interpretar porque las convenciones que importan
    /// (`org.nspasteboard.*`) no son tipos del sistema.
    public var types: Set<String>

    public var string: String?
    public var rtf: Data?

    /// Bundle ID que la app de origen declara mediante `org.nspasteboard.source`.
    /// Cuando viene, es más fiable que mirar qué app está en primer plano.
    public var declaredSourceBundleID: String?

    public init(
        changeCount: Int,
        types: Set<String> = [],
        string: String? = nil,
        rtf: Data? = nil,
        declaredSourceBundleID: String? = nil
    ) {
        self.changeCount = changeCount
        self.types = types
        self.string = string
        self.rtf = rtf
        self.declaredSourceBundleID = declaredSourceBundleID
    }
}

/// Identificadores de tipo que le importan al capturador.
public enum PasteboardTypes {
    // Convenciones de nspasteboard.org, respetadas por los gestores de
    // contraseñas y las utilidades de automatización. No son tipos del sistema:
    // son un acuerdo entre aplicaciones para marcar contenido que no debe
    // acabar en un historial.
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let source = "org.nspasteboard.source"

    public static let url = "public.url"
    public static let fileURL = "public.file-url"
    public static let rtf = "public.rtf"
    public static let utf8PlainText = "public.utf8-plain-text"
}
