import Foundation
import Testing
@testable import PasteCore

private let device = UUID()
private let safari = SourceApp(bundleID: "com.apple.Safari", name: "Safari")

private func engine(
    paused: Bool = false,
    excluded: Set<String> = [],
    maxTextBytes: Int = 5 * 1024 * 1024
) -> CaptureEngine {
    CaptureEngine(
        settings: CaptureSettings(
            isPaused: paused,
            excludedBundleIDs: excluded,
            maxTextBytes: maxTextBytes
        ),
        deviceID: device
    )
}

private func snapshot(
    changeCount: Int = 2,
    types: Set<String> = [PasteboardTypes.utf8PlainText],
    string: String? = nil,
    rtf: Data? = nil,
    declaredSource: String? = nil
) -> PasteboardSnapshot {
    PasteboardSnapshot(
        changeCount: changeCount,
        types: types,
        string: string,
        rtf: rtf,
        declaredSourceBundleID: declaredSource
    )
}

/// Extrae el elemento de una decisión, fallando el test si fue un descarte.
private func captured(_ decision: CaptureDecision) throws -> ClipboardItem {
    guard case .capture(let item) = decision else {
        Issue.record("Se esperaba captura, llegó \(decision)")
        throw CancellationError()
    }
    return item
}

// MARK: - Descartes

@Test func sinCambioEnElContadorNoSeCaptura() {
    let decision = engine().decide(
        snapshot(changeCount: 7, string: "hola"),
        lastChangeCount: 7,
        frontmost: safari
    )
    #expect(decision == .skip(.unchanged))
}

@Test func elContenidoOcultoNuncaSeCaptura() {
    let decision = engine().decide(
        snapshot(types: [PasteboardTypes.utf8PlainText, PasteboardTypes.concealed],
                 string: "hunter2"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.concealed))
}

@Test func elContenidoTransitorioNoSeCaptura() {
    for marca in [PasteboardTypes.transient, PasteboardTypes.autoGenerated] {
        let decision = engine().decide(
            snapshot(types: [PasteboardTypes.utf8PlainText, marca], string: "temporal"),
            lastChangeCount: 1,
            frontmost: safari
        )
        #expect(decision == .skip(.transient))
    }
}

@Test func enPausaNoSeCaptura() {
    let decision = engine(paused: true).decide(
        snapshot(string: "hola"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.paused))
}

@Test func lasAppsExcluidasNoSeCapturan() {
    let decision = engine(excluded: ["com.apple.Safari"]).decide(
        snapshot(string: "hola"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.excludedApp))
}

@Test func elContenidoSensibleGanaALaPausa() {
    // Estando en pausa, el motivo debe seguir siendo el contenido oculto: las
    // reglas de privacidad son duras y no dependen del estado de la app.
    let decision = engine(paused: true).decide(
        snapshot(types: [PasteboardTypes.utf8PlainText, PasteboardTypes.concealed],
                 string: "hunter2"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.concealed))
}

@Test func losFicherosSeDescartanHastaM2() {
    let decision = engine().decide(
        snapshot(types: [PasteboardTypes.fileURL, PasteboardTypes.utf8PlainText],
                 string: "/Users/yo/informe.pdf"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.unsupportedType))
}

@Test func elTextoDemasiadoGrandeNoSeCaptura() {
    let decision = engine(maxTextBytes: 10).decide(
        snapshot(string: String(repeating: "a", count: 11)),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.tooLarge))
}

@Test func elPortapapelesVacioNoSeCaptura() {
    #expect(engine().decide(snapshot(string: nil), lastChangeCount: 1, frontmost: safari)
        == .skip(.empty))
    // Solo espacios cuenta como vacío.
    #expect(engine().decide(snapshot(string: "   \n  "), lastChangeCount: 1, frontmost: safari)
        == .skip(.empty))
}

// MARK: - Detección de tipo

@Test func elTextoNormalSeGuardaComoTexto() throws {
    let item = try captured(engine().decide(
        snapshot(string: "git rebase -i HEAD~3"),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.kind == .text)
    #expect(item.plainText == "git rebase -i HEAD~3")
    #expect(item.urlHost == nil)
}

@Test func elTipoUrlDeclaradoGanaAlRtf() throws {
    // Un enlace copiado de una página web llega como RTF + texto + public.url.
    let item = try captured(engine().decide(
        snapshot(
            types: [PasteboardTypes.url, PasteboardTypes.rtf, PasteboardTypes.utf8PlainText],
            string: "https://github.com/groue/GRDB.swift",
            rtf: Data("{\\rtf1 enlace}".utf8)
        ),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.kind == .url)
    #expect(item.urlHost == "github.com")
    // Al no ser contenido con formato, el RTF no se guarda.
    #expect(item.richData == nil)
}

@Test func elTextoQueEsUnaUrlEnteraSeGuardaComoEnlace() throws {
    // Copiado desde un terminal: no declara public.url, llega pelado.
    let item = try captured(engine().decide(
        snapshot(string: "https://pasteapp.io/help"),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.kind == .url)
    #expect(item.urlHost == "pasteapp.io")
}

@Test func unaFraseQueContieneUnaUrlSigueSiendoTexto() throws {
    let item = try captured(engine().decide(
        snapshot(string: "mira esto https://pasteapp.io y dime"),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.kind == .text)
}

@Test func elRtfSeGuardaComoContenidoConFormatoYConservaElTextoPlano() throws {
    let rtf = Data("{\\rtf1\\ansi Hola \\b mundo\\b0}".utf8)
    let item = try captured(engine().decide(
        snapshot(types: [PasteboardTypes.rtf, PasteboardTypes.utf8PlainText],
                 string: "Hola mundo",
                 rtf: rtf),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.kind == .richText)
    #expect(item.richData == rtf)
    // Sin el texto plano, FTS5 no podría encontrarlo nunca.
    #expect(item.plainText == "Hola mundo")
}

@Test func elFormatoEntraEnElHashDelContenidoConFormato() {
    // Mismo texto, distinto formato: deben ser elementos distintos. Si el hash
    // ignorase el RTF, el segundo ascendería al primero y quedaría guardado un
    // formato que ya no corresponde a lo copiado.
    let base = { (rtf: String) in
        engine().decide(
            snapshot(types: [PasteboardTypes.rtf, PasteboardTypes.utf8PlainText],
                     string: "Hola",
                     rtf: Data(rtf.utf8)),
            lastChangeCount: 1,
            frontmost: safari
        )
    }
    guard case .capture(let negrita) = base("{\\rtf1\\b Hola}"),
          case .capture(let cursiva) = base("{\\rtf1\\i Hola}")
    else { Issue.record("Se esperaban dos capturas"); return }

    #expect(negrita.contentHash != cursiva.contentHash)
}

// MARK: - Origen

@Test func seAtribuyeALaAppEnPrimerPlano() throws {
    let item = try captured(engine().decide(
        snapshot(string: "hola"),
        lastChangeCount: 1,
        frontmost: SourceApp(bundleID: "com.microsoft.VSCode", name: "Code")
    ))
    #expect(item.sourceBundleID == "com.microsoft.VSCode")
    #expect(item.sourceAppName == "Code")
}

@Test func elOrigenDeclaradoGanaAlDePrimerPlano() throws {
    let item = try captured(engine().decide(
        snapshot(string: "hola", declaredSource: "com.apple.Notes"),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.sourceBundleID == "com.apple.Notes")
}

@Test func elOrigenDeclaradoConservaElNombreSiCoincideConPrimerPlano() throws {
    // La declaración solo trae el bundle ID; el nombre legible viene de
    // NSWorkspace y no debe perderse cuando ambos apuntan a la misma app.
    let item = try captured(engine().decide(
        snapshot(string: "hola", declaredSource: "com.apple.Safari"),
        lastChangeCount: 1,
        frontmost: safari
    ))
    #expect(item.sourceAppName == "Safari")
}

@Test func laExclusionSeAplicaAlOrigenDeclarado() {
    // Aunque en primer plano haya otra app, si el contenido declara venir de una
    // excluida hay que descartarlo.
    let decision = engine(excluded: ["com.1password.1password"]).decide(
        snapshot(string: "hunter2", declaredSource: "com.1password.1password"),
        lastChangeCount: 1,
        frontmost: safari
    )
    #expect(decision == .skip(.excludedApp))
}

@Test func sinAppDeOrigenSeCapturaIgual() throws {
    let item = try captured(engine().decide(
        snapshot(string: "hola"),
        lastChangeCount: 1,
        frontmost: nil
    ))
    #expect(item.sourceBundleID == nil)
    #expect(item.sourceDeviceID == device)
}
